export const WORD_WITH_SPACE_REGEX = /[^a-zA-Z ]/g;
export const USERNAME_SPACE_REGEX = /[^a-zA-Z_\d]/g;
export const EMAIL_SPACE_REGEX = /[^a-zA-Z0-9!@#$%^&*._-]/g;
export const LINK_SPACE_REGEX = /[^a-zA-Z0-9@:%._\+~#?&//=]/g;
export const PAN_SPACE_REGEX = /[^a-zA-Z0-9]/g;
export const NUMBER_SPACE_REGEX = /[^0-9]/g;
export const NUMBER_REGEX = /\D/g;
export const ALPHABET_WITH_SPACE_REGEX = /^([a-zA-Z0-9]+\s?)*$/;
export const GST_REGEX = /\d{2}[A-Z]{5}\d{4}[A-Z]{1}[A-Z\d]{1}[Z]{1}[A-Z\d]{1}/;
export const USERNAME_REGEX = /^[a-zA-Z][a-zA-Z0-9_]{6,19}$/;
export const PASSWORD_REGEX = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*])(?=.*[a-zA-Z]).{8,}$/;
export const EMAIL_REGEX = /^(()|([\w-\\.]+@([\w-]+\.)+[\w-]{2,4}))?$/;
export const PINCODE_REGEX = /^[1-9]{1}[0-9]{2}[0-9]{3}$/;
export const MOBILE_NUMBER_REGEX = /^[6-9]\d{9}$/;
export const ADDRESS_REGEX = /^[^\s]+[A-Za-z0-9'\.\-\s\,].*/;
export const BANKNAME_REGEX = /^([a-zA-Z0-9]+\s?)*$/;
export const ACCOUNTNUMBER_REGEX = /^[0-9]{9,18}$/;
export const AADHAR_NUMBER_REGEX = /^([0-9]{4}[0-9]{4}[0-9]{4}$)|([0-9]{4}\s[0-9]{4}\s[0-9]{4}$)|([0-9]{4}-[0-9]{4}-[0-9]{4}$)/;
export const PAN_NUMBER_REGEX = /([A-Z]){5}([0-9]){4}([A-Z]){1}$/;
export const FULLNAME_REGEX = /^[a-zA-Z]{2,40}( [a-zA-Z]{2,40})+$/;
export const WEBSITE_REGEX = /(?:^|\s)(https?:\/\/\S+\.(?:com|org))(?:\s|$)/;
export const UPIIDREGEX = /^[a-zA-Z0-9._]+@[a-zA-Z0-9._]+$/;
export const IFSCCODEREGEX = /^[A-Z]{4}0[A-Z0-9]{6}$/;